//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Page_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Page_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NBack.Page_Resources", typeof(Page_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another square will appear, and another letter will be said. Remember these, too..
        /// </summary>
        internal static string Another_Will_Appear {
            get {
                return ResourceManager.GetString("Another_Will_Appear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you get better, you will need to remember what happened 3 times ago, etc..
        /// </summary>
        internal static string As_Get_Better {
            get {
                return ResourceManager.GetString("As_Get_Better", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, another set will appear.  You need to remember what happened the time before last.  Here, we&apos;ll break down the possibilities..
        /// </summary>
        internal static string Break_It_Down {
            get {
                return ResourceManager.GetString("Break_It_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed all 20 sessions. Congratulations!  .
        /// </summary>
        internal static string Completed_All {
            get {
                return ResourceManager.GetString("Completed_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue and do the same thing for the next sets..
        /// </summary>
        internal static string Continue_Round {
            get {
                return ResourceManager.GetString("Continue_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete the same training as performed in the study, continue for 20 sessions..
        /// </summary>
        internal static string Continue_Sessions {
            get {
                return ResourceManager.GetString("Continue_Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Luck!.
        /// </summary>
        internal static string Good_Luck {
            get {
                return ResourceManager.GetString("Good_Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And if the same letter is said as the time before last, press the &quot;L&quot; key. (We&apos;re not showing it, but a square would normally also appear.).
        /// </summary>
        internal static string If_Audio {
            get {
                return ResourceManager.GetString("If_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If they&apos;re both the same as they were on the time before last, press both &quot;A&quot; and &quot;L&quot;..
        /// </summary>
        internal static string If_Both_Happen {
            get {
                return ResourceManager.GetString("If_Both_Happen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the square appears in the same location as the time before last, press the &quot;A&quot; key. ( For simplicity, we&apos;re going to omit the letter for a moment.).
        /// </summary>
        internal static string If_Square {
            get {
                return ResourceManager.GetString("If_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Roughly, this correlates to an increase of {0}% in intelligence (gF)..
        /// </summary>
        internal static string Increase_GF {
            get {
                return ResourceManager.GetString("Increase_GF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You had an average N level of {0}.  .
        /// </summary>
        internal static string Mean_N {
            get {
                return ResourceManager.GetString("Mean_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number tells you how far back to remember.  It starts by telling you to remember what happened 2 times ago.  That is, the time before last..
        /// </summary>
        internal static string NBack_Num_Tells_You {
            get {
                return ResourceManager.GetString("NBack_Num_Tells_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice this number..
        /// </summary>
        internal static string Notice_NBack_Num {
            get {
                return ResourceManager.GetString("Notice_NBack_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember where the square appears and what letter is said..
        /// </summary>
        internal static string Remember_Where {
            get {
                return ResourceManager.GetString("Remember_Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset__Button {
            get {
                return ResourceManager.GetString("Reset__Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that your speakers are on.  This game requires that you listen to sounds..
        /// </summary>
        internal static string Speakers_On {
            get {
                return ResourceManager.GetString("Speakers_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start_Button {
            get {
                return ResourceManager.GetString("Start_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop_Button {
            get {
                return ResourceManager.GetString("Stop_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch and listen.  A square will appear and a letter will be said out loud..
        /// </summary>
        internal static string Watch_First_Trial {
            get {
                return ResourceManager.GetString("Watch_First_Trial", resourceCulture);
            }
        }
    }
}
